// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxxI52pbToxCUjHi3RfrOjV8TYbDSOFwI',
    appId: '1:843234342043:web:66704201bff08accdc423e',
    messagingSenderId: '843234342043',
    projectId: 'chatapp-1d64d',
    authDomain: 'chatapp-1d64d.firebaseapp.com',
    storageBucket: 'chatapp-1d64d.firebasestorage.app',
    measurementId: 'G-7V1D3FW5BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV7RkVgLpugMGa6uelU_q2TKcY93D-TBc',
    appId: '1:843234342043:android:e4f762671fabcb7bdc423e',
    messagingSenderId: '843234342043',
    projectId: 'chatapp-1d64d',
    storageBucket: 'chatapp-1d64d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe4dKgoUDxjj9c-8tmHnQcr2RRfMdm0AQ',
    appId: '1:843234342043:ios:aabc3703a09989b5dc423e',
    messagingSenderId: '843234342043',
    projectId: 'chatapp-1d64d',
    storageBucket: 'chatapp-1d64d.firebasestorage.app',
    iosClientId: '843234342043-rsqnbe8va7eh5mnlg30mtnfjpmnqq0la.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}